const data = [
  {
    _id: 'k_benatchba@esi.dz',
    nomComplet: 'Karima Benatchba',
    GradeEnsegnement: null,
    qualité: 'Chercheure',
    GradeRecherche: 'Maitre de recherche',
    H_index: 20,
    EtablissementOrigine: 'ESI',
    statut: 'Actif',
    Diplome: 'Doctorat',
    Equipe: 'Optimisation',
  },
  {
    _id: 'mouloud.koudil@esi.dz',
    nomComplet: 'Mouloud Koudil',
    GradeEnsegnement: 'MCA',
    qualité: 'Enseignat-Chercheur',
    GradeRecherche: 'Directeur de recherche',
    H_index: 27,
    EtablissementOrigine: 'ESI',
    statut: 'Actif',
    Equipe: 'EIAH',
    Diplome: 'Doctorat',
  },
  {
    _id: 'b_khelouat@esi.dz',
    nomComplet: 'Boualem Khelouat',
    GradeEnsegnement: 'MCB',
    qualité: 'Enseignat-Chercheure',
    GradeRecherche: 'Maitre de recherche',
    H_index: 12,
    EtablissementOrigine: 'ESI',
    statut: 'Actif',
    Diplome: 'Doctorat',
    Equipe: 'SURES',
  },
  {
    _id: 'f_sitayeb@esi.dz',
    nomComplet: 'Fatima Benbouzid-Si Tayeb',
    GradeEnsegnement: 'MAA',
    qualité: 'Enseignat-Chercheure',
    GradeRecherche: 'Maitre de recherche',
    H_index: 10,
    EtablissementOrigine: 'ESI',
    statut: 'Actif',
    Diplome: 'Doctorat',
    Equipe: 'SURES',
  },
  {
    _id: 'k_benatchba@esi.dz',
    nomComplet: 'Karima Benatchba',
    GradeEnsegnement: null,
    qualité: 'Chercheure',
    GradeRecherche: 'Maitre de recherche',
    H_index: 20,
    EtablissementOrigine: 'ESI',
    statut: 'Actif',
    Diplome: 'Doctorat',
    Equipe: 'Optimisation',
  },
  {
    _id: 'mouloud.koudil@esi.dz',
    nomComplet: 'Mouloud Koudil',
    GradeEnsegnement: 'MCA',
    qualité: 'Enseignat-Chercheur',
    GradeRecherche: 'Directeur de recherche',
    H_index: 27,
    EtablissementOrigine: 'ESI',
    statut: 'Actif',
    Equipe: 'EIAH',
    Diplome: 'Doctorat',
  },
  {
    _id: 'b_khelouat@esi.dz',
    nomComplet: 'Boualem Khelouat',
    GradeEnsegnement: 'MCB',
    qualité: 'Enseignat-Chercheure',
    GradeRecherche: 'Maitre de recherche',
    H_index: 12,
    EtablissementOrigine: 'ESI',
    statut: 'Actif',
    Diplome: 'Doctorat',
    Equipe: 'SURES',
  },
  {
    _id: 'f_sitayeb@esi.dz',
    nomComplet: 'Fatima Benbouzid-Si Tayeb',
    GradeEnsegnement: 'MAA',
    qualité: 'Enseignat-Chercheure',
    GradeRecherche: 'Maitre de recherche',
    H_index: 10,
    EtablissementOrigine: 'ESI',
    statut: 'Actif',
    Diplome: 'Doctorat',
    Equipe: 'SURES',
  },
  {
    _id: 'k_benatchba@esi.dz',
    nomComplet: 'Karima Benatchba',
    GradeEnsegnement: null,
    qualité: 'Chercheure',
    GradeRecherche: 'Maitre de recherche',
    H_index: 20,
    EtablissementOrigine: 'ESI',
    statut: 'Actif',
    Diplome: 'Doctorat',
    Equipe: 'Optimisation',
  },
  {
    _id: 'mouloud.koudil@esi.dz',
    nomComplet: 'Mouloud Koudil',
    GradeEnsegnement: 'MCA',
    qualité: 'Enseignat-Chercheur',
    GradeRecherche: 'Directeur de recherche',
    H_index: 27,
    EtablissementOrigine: 'ESI',
    statut: 'Actif',
    Equipe: 'EIAH',
    Diplome: 'Doctorat',
  },
  {
    _id: 'b_khelouat@esi.dz',
    nomComplet: 'Boualem Khelouat',
    GradeEnsegnement: 'MCB',
    qualité: 'Enseignat-Chercheure',
    GradeRecherche: 'Maitre de recherche',
    H_index: 12,
    EtablissementOrigine: 'ESI',
    statut: 'Actif',
    Diplome: 'Doctorat',
    Equipe: 'SURES',
  },
  {
    _id: 'f_sitayeb@esi.dz',
    nomComplet: 'Fatima Benbouzid-Si Tayeb',
    GradeEnsegnement: 'MAA',
    qualité: 'Enseignat-Chercheure',
    GradeRecherche: 'Maitre de recherche',
    H_index: 10,
    EtablissementOrigine: 'ESI',
    statut: 'Actif',
    Diplome: 'Doctorat',
    Equipe: 'SURES',
  },
  {
    _id: 'k_benatchba@esi.dz',
    nomComplet: 'Karima Benatchba',
    GradeEnsegnement: null,
    qualité: 'Chercheure',
    GradeRecherche: 'Maitre de recherche',
    H_index: 20,
    EtablissementOrigine: 'ESI',
    statut: 'Actif',
    Diplome: 'Doctorat',
    Equipe: 'Optimisation',
  },
  {
    _id: 'mouloud.koudil@esi.dz',
    nomComplet: 'Mouloud Koudil',
    GradeEnsegnement: 'MCA',
    qualité: 'Enseignat-Chercheur',
    GradeRecherche: 'Directeur de recherche',
    H_index: 27,
    EtablissementOrigine: 'ESI',
    statut: 'Actif',
    Equipe: 'EIAH',
    Diplome: 'Doctorat',
  },
  {
    _id: 'b_khelouat@esi.dz',
    nomComplet: 'Boualem Khelouat',
    GradeEnsegnement: 'MCB',
    qualité: 'Enseignat-Chercheure',
    GradeRecherche: 'Maitre de recherche',
    H_index: 12,
    EtablissementOrigine: 'ESI',
    statut: 'Actif',
    Diplome: 'Doctorat',
    Equipe: 'SURES',
  },
  {
    _id: 'f_sitayeb@esi.dz',
    nomComplet: 'Fatima Benbouzid-Si Tayeb',
    GradeEnsegnement: 'MAA',
    qualité: 'Enseignat-Chercheure',
    GradeRecherche: 'Maitre de recherche',
    H_index: 10,
    EtablissementOrigine: 'ESI',
    statut: 'Actif',
    Diplome: 'Doctorat',
    Equipe: 'SURES',
  },
  {
    _id: 'k_benatchba@esi.dz',
    nomComplet: 'Karima Benatchba',
    GradeEnsegnement: null,
    qualité: 'Chercheure',
    GradeRecherche: 'Maitre de recherche',
    H_index: 20,
    EtablissementOrigine: 'ESI',
    statut: 'Actif',
    Diplome: 'Doctorat',
    Equipe: 'Optimisation',
  },
  {
    _id: 'mouloud.koudil@esi.dz',
    nomComplet: 'Mouloud Koudil',
    GradeEnsegnement: 'MCA',
    qualité: 'Enseignat-Chercheur',
    GradeRecherche: 'Directeur de recherche',
    H_index: 27,
    EtablissementOrigine: 'ESI',
    statut: 'Actif',
    Equipe: 'EIAH',
    Diplome: 'Doctorat',
  },
  {
    _id: 'b_khelouat@esi.dz',
    nomComplet: 'Boualem Khelouat',
    GradeEnsegnement: 'MCB',
    qualité: 'Enseignat-Chercheure',
    GradeRecherche: 'Maitre de recherche',
    H_index: 12,
    EtablissementOrigine: 'ESI',
    statut: 'Actif',
    Diplome: 'Doctorat',
    Equipe: 'SURES',
  },
  {
    _id: 'f_sitayeb@esi.dz',
    nomComplet: 'Fatima Benbouzid-Si Tayeb',
    GradeEnsegnement: 'MAA',
    qualité: 'Enseignat-Chercheure',
    GradeRecherche: 'Maitre de recherche',
    H_index: 10,
    EtablissementOrigine: 'ESI',
    statut: 'Actif',
    Diplome: 'Doctorat',
    Equipe: 'SURES',
  },
  {
    _id: 'k_benatchba@esi.dz',
    nomComplet: 'Karima Benatchba',
    GradeEnsegnement: null,
    qualité: 'Chercheure',
    GradeRecherche: 'Maitre de recherche',
    H_index: 20,
    EtablissementOrigine: 'ESI',
    statut: 'Actif',
    Diplome: 'Doctorat',
    Equipe: 'Optimisation',
  },
  {
    _id: 'mouloud.koudil@esi.dz',
    nomComplet: 'Mouloud Koudil',
    GradeEnsegnement: 'MCA',
    qualité: 'Enseignat-Chercheur',
    GradeRecherche: 'Directeur de recherche',
    H_index: 27,
    EtablissementOrigine: 'ESI',
    statut: 'Actif',
    Equipe: 'EIAH',
    Diplome: 'Doctorat',
  },
  {
    _id: 'b_khelouat@esi.dz',
    nomComplet: 'Boualem Khelouat',
    GradeEnsegnement: 'MCB',
    qualité: 'Enseignat-Chercheure',
    GradeRecherche: 'Maitre de recherche',
    H_index: 12,
    EtablissementOrigine: 'ESI',
    statut: 'Actif',
    Diplome: 'Doctorat',
    Equipe: 'SURES',
  },
  {
    _id: 'f_sitayeb@esi.dz',
    nomComplet: 'Fatima Benbouzid-Si Tayeb',
    GradeEnsegnement: 'MAA',
    qualité: 'Enseignat-Chercheure',
    GradeRecherche: 'Maitre de recherche',
    H_index: 10,
    EtablissementOrigine: 'ESI',
    statut: 'Actif',
    Diplome: 'Doctorat',
    Equipe: 'SURES',
  },
  {
    _id: 'k_benatchba@esi.dz',
    nomComplet: 'Karima Benatchba',
    GradeEnsegnement: null,
    qualité: 'Chercheure',
    GradeRecherche: 'Maitre de recherche',
    H_index: 20,
    EtablissementOrigine: 'ESI',
    statut: 'Actif',
    Diplome: 'Doctorat',
    Equipe: 'Optimisation',
  },
  {
    _id: 'mouloud.koudil@esi.dz',
    nomComplet: 'Mouloud Koudil',
    GradeEnsegnement: 'MCA',
    qualité: 'Enseignat-Chercheur',
    GradeRecherche: 'Directeur de recherche',
    H_index: 27,
    EtablissementOrigine: 'ESI',
    statut: 'Actif',
    Equipe: 'EIAH',
    Diplome: 'Doctorat',
  },
  {
    _id: 'b_khelouat@esi.dz',
    nomComplet: 'Boualem Khelouat',
    GradeEnsegnement: 'MCB',
    qualité: 'Enseignat-Chercheure',
    GradeRecherche: 'Maitre de recherche',
    H_index: 12,
    EtablissementOrigine: 'ESI',
    statut: 'Actif',
    Diplome: 'Doctorat',
    Equipe: 'SURES',
  },
  {
    _id: 'f_sitayeb@esi.dz',
    nomComplet: 'Fatima Benbouzid-Si Tayeb',
    GradeEnsegnement: 'MAA',
    qualité: 'Enseignat-Chercheure',
    GradeRecherche: 'Maitre de recherche',
    H_index: 10,
    EtablissementOrigine: 'ESI',
    statut: 'Actif',
    Diplome: 'Doctorat',
    Equipe: 'SURES',
  },
];
export default data;
